(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const VK='https://vk.ru/garant_bani';
const section=document.createElement('section');section.id='contact';section.className='contact-hub section';
section.innerHTML='<div class="container hub-grid"><div><span class="eyebrow">ОТ ВАШЕГО ОТДЫХА — ОДИН ШАГ</span><h2>Выбирайте вечер в бане.<br><em>Не строительный проект.</em></h2><p>Не нужно разбираться в комплектациях заранее. Расскажите, где находится дача. Поможем выбрать готовую баню, выяснить условия доставки и установки.</p><div class="hub-chips"><span>Без оплаты за консультацию</span><span>Ответ удобным способом</span></div></div><div class="hub-actions"><button type="button" data-contact-flow="quote" class="hub-choice primary"><b>01</b><span><strong>Рассчитать баню для моей дачи</strong><small>Комплектация, доставка и установка</small></span>→</button><button type="button" data-contact-flow="callback" class="hub-choice"><b>02</b><span><strong>Оставьте телефон — перезвоним</strong><small>Короткая форма без подбора модели</small></span>→</button><a class="hub-choice" href="'+VK+'" target="_blank" rel="noopener noreferrer"><b>VK</b><span><strong>Написать ВКонтакте</strong><small>Открыть сообщество компании</small></span>↗</a><p class="hub-footnote">Удобнее Telegram, MAX или WhatsApp? Выберите канал в заявке. Ссылки прямых чатов добавим после подтверждения компании.</p></div></div>';
$('.closing')?.before(section);
const dialog=document.createElement('dialog');dialog.className='new-lead';dialog.id='contactDialog';dialog.setAttribute('aria-labelledby','contactTitle');
dialog.innerHTML='<div class="lead-shell"><button type="button" class="lead-close" aria-label="Закрыть">×</button><span class="eyebrow" id="leadFlowTitle">ПОДБОР БАНИ</span><h2 id="contactTitle">Ваш отдых начинается с заявки</h2><p class="lead-subtitle">Поможем выбрать готовую баню и узнать условия доставки на вашу дачу.</p><form id="newLeadForm" novalidate><label class="lead-field">Как к вам обращаться? *<input id="newName" autocomplete="name" maxlength="80" placeholder="Например, Алексей" required></label><div id="leadExtra" class="lead-extra"><div class="lead-pair"><label class="lead-field">Модель<select id="newModel"><option>Пока выбираю</option><option>Квадро Хаус</option><option>Квадро</option><option>Парус</option><option>Викинг</option></select></label><label class="lead-field">Где находится дача?<input id="newCity" maxlength="120" placeholder="Район или населённый пункт"></label></div><label class="lead-field">Что важно?<textarea id="newWish" rows="2" maxlength="500" placeholder="Парилка, место для отдыха, дополнительные опции…"></textarea></label></div><fieldset class="lead-methods"><legend>Как с вами связаться? *</legend><label><input type="radio" name="answer" value="phone" checked> Позвонить</label><label><input type="radio" name="answer" value="telegram"> Telegram</label><label><input type="radio" name="answer" value="max"> MAX</label><label><input type="radio" name="answer" value="whatsapp"> WhatsApp</label><label><input type="radio" name="answer" value="vk"> ВКонтакте</label></fieldset><label class="lead-field"><span id="leadAddressTitle">Ваш телефон *</span><input id="newContact" type="tel" inputmode="tel" autocomplete="tel" placeholder="+7 9XX XXX-XX-XX" maxlength="100" required><small id="leadContactHelp">Для ответа на ваш запрос</small></label><label class="lead-consent"><input id="newConsent" type="checkbox" required><span>Согласен(на) на обработку контактных данных для ответа на обращение. <a href="https://www.garant-bany.ru/politika" target="_blank" rel="noopener noreferrer">Политика компании</a>.</span></label><div id="newLeadError" role="alert" aria-live="polite"></div><button class="btn btn-primary btn-full" type="submit">Подготовить обращение →</button><small class="lead-note">Тестовая версия: заявка не отправляется и не сохраняется автоматически.</small></form><div id="leadResult" hidden><h3>Обращение подготовлено</h3><p>Это прототип. Мы не получили ваши данные. Скопируйте текст и отправьте его компании ВКонтакте.</p><pre id="leadText"></pre><div class="lead-result-actions"><button id="leadCopy" class="btn btn-primary" type="button">Скопировать текст</button><a href="'+VK+'" class="btn btn-light" target="_blank" rel="noopener noreferrer">Открыть ВКонтакте ↗</a></div><p id="leadCopyStatus" aria-live="polite"></p><button id="leadEdit" type="button" class="lead-edit">Изменить данные</button></div></div>';
document.body.append(dialog);
let flow='quote';const form=$('#newLeadForm'),err=$('#newLeadError');
function channel(){return $('input[name="answer"]:checked',form)?.value||'phone'}
function syncChannel(){const c=channel(),phone=['phone','whatsapp','max'].includes(c),el=$('#newContact');el.value='';el.type=phone?'tel':'text';el.inputMode=phone?'tel':'text';el.placeholder=phone?'+7 9XX XXX-XX-XX':c==='telegram'?'@username или ссылка t.me/…':'Ник или ссылка на профиль';$('#leadAddressTitle').textContent=(phone?'Ваш телефон':'Как вас найти')+' *';$('#leadContactHelp').textContent=phone?'Для звонка или сообщения укажите номер телефона':'Укажите конкретный ник или ссылку';err.textContent=''}
function open(next,model){flow=next==='callback'?'callback':'quote';form.hidden=false;$('#leadResult').hidden=true;err.textContent='';$('#leadExtra').hidden=flow==='callback';$('#leadFlowTitle').textContent=flow==='callback'?'ОБРАТНЫЙ ЗВОНОК':'ПОДБОР БАНИ';$('#contactTitle').textContent=flow==='callback'?'Оставьте телефон — перезвоним':'Подберём баню для вашей дачи';$('.lead-subtitle').textContent=flow==='callback'?'Короткая форма, чтобы уточнить ваши вопросы':'Модель, комплектация, доставка и установка — без строительного марафона';if(model&&$('#newModel'))$('#newModel').value=model;if(flow==='callback'){$('input[name="answer"][value="phone"]',form).checked=true;syncChannel()}dialog.showModal();$('#newName').focus()}
document.addEventListener('click',e=>{const el=e.target.closest('[data-open-lead],[data-pick-model],#configSubmit,[data-contact-flow]');if(!el)return;e.preventDefault();e.stopImmediatePropagation();open(el.dataset.contactFlow,el.dataset.pickModel||$('#configModel')?.value||'')},true);
$('.lead-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
$$('input[name="answer"]',form).forEach(x=>x.addEventListener('change',syncChannel));
function valid(c,v){const digits=v.replace(/\D/g,'');if(['phone','whatsapp','max'].includes(c))return /^\+?[\d\s()\-]+$/.test(v)&&digits.length>=10&&digits.length<=11;if(c==='telegram')return /^@[A-Za-z0-9_]{5,32}$/.test(v)||/^https?:\/\/(?:t\.me|telegram\.me)\/[A-Za-z0-9_]{5,32}\/?$/i.test(v);return /^https?:\/\//i.test(v)||/^@?[\w.\-]{4,60}$/.test(v)}
form.addEventListener('submit',e=>{e.preventDefault();const name=$('#newName').value.trim(),c=channel(),contact=$('#newContact').value.trim();if(name.length<2){err.textContent='Укажите имя — минимум 2 символа';$('#newName').focus();return}if(!valid(c,contact)){err.textContent='Проверьте контакт для выбранного способа связи';$('#newContact').focus();return}if(!$('#newConsent').checked){err.textContent='Нужно согласие на обработку контактных данных';$('#newConsent').focus();return}err.textContent='';const labels={phone:'Звонок',telegram:'Telegram',max:'MAX',whatsapp:'WhatsApp',vk:'ВКонтакте'};let parts=[flow==='callback'?'Здравствуйте! Прошу перезвонить по поводу готовой бани.':'Здравствуйте! Хочу подобрать готовую баню для дачи.','Имя: '+name,'Связь: '+labels[c],'Контакт: '+contact];if(flow!=='callback'){parts.push('Модель: '+$('#newModel').value);const loc=$('#newCity').value.trim(),wish=$('#newWish').value.trim();if(loc)parts.push('Место установки: '+loc);if(wish)parts.push('Пожелания: '+wish);parts.push('Уточните стоимость, доставку, установку и условия первого использования.')}$('#leadText').textContent=parts.join('\n');form.hidden=true;$('#leadResult').hidden=false;$('#leadCopyStatus').textContent=''});
$('#leadCopy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#leadText').textContent);$('#leadCopyStatus').textContent='Скопировано. Отправьте сообщение компании.'}catch{$('#leadCopyStatus').textContent='Скопируйте текст вручную.'}});
$('#leadEdit').addEventListener('click',()=>{$('#leadResult').hidden=true;form.hidden=false});
const hero=$('#heroLead'),sun='Своя баня на даче — для пятничных вечеров, близких и настоящего отдыха. Изготавливаем заранее и доставляем готовой: без месяцев стройки у вас на участке.',rain='На даче льёт дождь? Пусть. Внутри тепло, горит свет и можно забыть о рабочей неделе. Собирайте близких — вечер только начинается.';if(hero)hero.textContent=sun;$$('[data-weather]').forEach(b=>b.addEventListener('click',()=>{if(hero)hero.textContent=b.dataset.weather==='rain'?rain:sun}));
$('.hero-buttons')?.insertAdjacentHTML('afterend','<div class="hero-extra-cta"><button type="button" data-contact-flow="callback">Перезвоните мне →</button><a href="'+VK+'" target="_blank" rel="noopener noreferrer">Написать ВКонтакте ↗</a></div>');
const i=$('.intro h2');if(i)i.innerHTML='Не ждите отпуска.<br><em>Ваш отдых уже на даче.</em>';const end=$('.closing h2');if(end)end.innerHTML='Не откладывайте<br>хорошие выходные<br><em>на потом.</em>';
const nav=$('.nav');if(nav)nav.insertAdjacentHTML('beforeend','<a href="#contact">Связаться</a>');
})();
