import {test} from 'node:test';import assert from 'node:assert/strict';
import {calculateQuote,resolveOptions,formatMoney} from '../assets/js/quote-engine.js';
import {PRICEBOOK} from '../data/pricebook.js';
const q=(patch={})=>calculateQuote({modelId:'kvadro-house',sizeId:'500',optionIds:[],...patch});
const required=PRICEBOOK.bundle.optionIds;
test('T01 basic no options is 659k',()=>assert.equal(q().total,659000));
test('T02 bundle total 857k',()=>assert.equal(q({optionIds:required,bundleId:'family-comfort-demo'}).total,857000));
test('T03 bundle original sum 927k',()=>assert.equal(q({optionIds:required,bundleId:'family-comfort-demo'}).beforeDiscount,927000));
test('T04 bundle discount exactly 70k',()=>assert.equal(q({optionIds:required,bundleId:'family-comfort-demo'}).discount,70000));
test('T05 bundle has five exact options',()=>assert.deepEqual(q({optionIds:required}).optionIds,required));
test('T06 bundle breaks if one option removed',()=>assert.equal(q({optionIds:required.slice(0,-1),bundleId:'family-comfort-demo'}).bundleApplied,false));
test('T07 bundle additional option no double discount',()=>assert.equal(q({optionIds:[...required,'firebox'],bundleId:'family-comfort-demo'}).discount,70000));
test('T08 progressive 2 options 3%',()=>assert.equal(q({optionIds:['firebox','window']}).discount,840));
test('T09 progressive 3 options 5%',()=>assert.equal(q({optionIds:['firebox','window','steam-led']}).discount,2750));
test('T10 progressive 4 options 7%',()=>assert.equal(q({optionIds:['firebox','window','steam-led','porch']}).discount,5530));
test('T11 progressive 5 options 10%',()=>assert.equal(q({optionIds:required}).discount,26800));
test('T12 removing an option recalculates all',()=>assert.equal(q({optionIds:['firebox','window','steam-led']}).discount-q({optionIds:['firebox','window']}).discount,1910));
test('T13 same door variants forbidden',()=>assert.throws(()=>q({optionIds:['glass-door-170','glass-door-180']}),/INCOMPATIBLE/));
test('T14 metal & glass doors forbidden',()=>assert.throws(()=>q({optionIds:['metal-door','glass-door-190']}),/INCOMPATIBLE/));
test('T15 unknown option forbidden',()=>assert.throws(()=>q({optionIds:['magic-spa']}),/UNKNOWN/));
test('T16 duplicate option forbidden',()=>assert.throws(()=>q({optionIds:['window','window']}),/DUPLICATE/));
test('T17 house 400 unavailable',()=>assert.throws(()=>q({sizeId:'400'}),/UNAVAILABLE/));
test('T18 unknown model forbidden',()=>assert.throws(()=>q({modelId:'alien'}),/UNKNOWN_MODEL/));
test('T19 unknown size forbidden',()=>assert.throws(()=>q({sizeId:'200'}),/UNAVAILABLE/));
test('T20 bundle mismatch size invalid',()=>assert.equal(q({sizeId:'600',optionIds:required,bundleId:'family-comfort-demo'}).bundleApplied,false));
test('T21 no discounts with one option',()=>assert.equal(q({optionIds:['window']}).discount,0));
test('T22 no options total nonnegative',()=>assert.ok(q().total>=0));
test('T23 no invented delivery price',()=>assert.equal(q().deliveryKnown,false));
test('T24 demo status explicitly exposed',()=>assert.equal(q().pricebookStatus,'DEMO_ONLY'));
test('T25 pricebook version carried',()=>assert.equal(q().pricebookVersion,PRICEBOOK.version));
test('T26 all models and sizes calculate',()=>{for(const m of PRICEBOOK.models)for(const size of Object.keys(m.sizes))assert.equal(q({modelId:m.id,sizeId:size}).total,m.sizes[size]);});
test('T27 invalid options must be array',()=>assert.throws(()=>resolveOptions('steam-led'),/ARRAY/));
test('T28 wrong ID type forbidden',()=>assert.throws(()=>resolveOptions([3]),/INVALID_OPTION/));
test('T29 money format Ruble symbol',()=>assert.match(formatMoney(857000),/857\s?000\s?₽/));
test('T30 invalid pricebook fails closed',()=>assert.throws(()=>calculateQuote({}, {...PRICEBOOK,status:'UNVERIFIED'}),/UNAPPROVED/));
test('T31 negative base fails',()=>assert.throws(()=>calculateQuote({}, {...PRICEBOOK,models:[{...PRICEBOOK.models[3],sizes:{500:-5}}]}),/INVALID_BASE/));
test('T32 quote original total is sum-discount',()=>{for(const ids of [[],['window'],['window','porch'],required]){const r=q({optionIds:ids});assert.equal(r.total,r.basePrice+r.optionsSubtotal-r.discount);}});
test('T33 cannot apply other ID as bundle',()=>assert.equal(q({optionIds:required,bundleId:'unknown'}).discountType,'progressive'));
test('T34 order of selected independent options preserves total',()=>assert.equal(q({optionIds:['aspen','window']}).total,q({optionIds:['window','aspen']}).total));
test('T35 progressive discount only on add-ons',()=>assert.equal(q({optionIds:['aspen','window']}).discount,Math.round((129000+9000)*.03)));
test('T36 false bundle with no options no discount',()=>assert.equal(q({bundleId:'family-comfort-demo'}).discount,0));
